// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyvdmhvpwfnyypmxivzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5dmRtaHZwd2ZueXlwbXhpdnpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMjQ1MDcsImV4cCI6MjA3MzkwMDUwN30.CwKlITQpb7TxC2qosp4TZA8wsyAyg_mnDqSd_DEKKaY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});